### ISSUE TITLE
The pretained model (trrain on seen classes and test on unseen classes of the same dataset) could not match the result in paper.

### ISSUE THREAD

**Issue by AutomanHan** [MendelXu/zsseg.baseline#19]
I download the pretrained model [Trained Model](https://drive.google.com/file/d/1jDmR4fL5Wm0UyMDd5LhsOl6T2RX2X9R5/view?usp=sharing), and evaluate on the cocostuff dataset. The results of Directly using CLIP vision eccoder without tuning are 21.01 mIoU and  26.95 mIoU for seen and unseen respectively. However, the results of paper are 26.8 mIoU and 29.7 mIoU. Are the results reasonable?
![image](https://user-images.githubusercontent.com/24837080/209339859-232b11a4-a50a-435e-a1e9-4e0441360971.png)

**Comment by MendelXu** [comment]
I didn't check it carefully buy I think it is due to the stability issue of the learnable prompts. The result in the paper is trained with an old version code and the provided model is re-trained with the reformatted code (As reported by other people, even with the same code, the stability issue still exists. But I haven't found a good solution for the problem.). However, you can find the old model in[ Drive](https://drive.google.com/file/d/1Rf4J9xhZgt29DE0NLAbxP8xDv00RlUFb/view?usp=share_link). By modifying the current code, it should be able to load the old weights. Or you can ask me for the old version code through email.

**Comment by ylong4** [comment]
Hello，I download the pretrained model Trained Model and follow the same Command line, but I got [AssertionError: Non-existent key:  MODEL.WEIGHTST] , please help me.
![image](https://user-images.githubusercontent.com/95207674/224064673-3819c7e8-49e1-47ad-9da4-8884832574d9.png)
![image](https://user-images.githubusercontent.com/95207674/224065194-554c9842-29de-4e32-ae36-6dac23cf7c8b.png)
